default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: katherinemccann
  password: <%= ENV.fetch("PG_PASSWORD") { '' } %>
  host: <%= ENV.fetch("PG_HOST") { 'localhost' } %>

development:
  <<: *default
  database: writing_outlet_development

test:
  <<: *default
  database: writing_outlet_test

production:
  <<: *default
  database: writing_outlet_production
  username: writing_outlet_production
  password: <%= ENV.fetch('WRITING_OUTLET_DATABASE_PASSWORD', '') %>
